"""ok review

Revision ID: 12217c5e40e8
Revises: fac521ca3ac2
Create Date: 2024-11-10 22:18:50.105040

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '12217c5e40e8'
down_revision = 'fac521ca3ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
