"""new models

Revision ID: 21d732a671cb
Revises: 271b192d0dd6
Create Date: 2024-10-27 22:43:26.142108

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '21d732a671cb'
down_revision = '271b192d0dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
