"""created_date common model add datetime.now

Revision ID: 271097c169a6
Revises: ec148c683b34
Create Date: 2024-10-27 15:26:29.912913

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '271097c169a6'
down_revision = 'ec148c683b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
