"""new models

Revision ID: 271b192d0dd6
Revises: 462e34736875
Create Date: 2024-10-27 22:16:26.033916

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '271b192d0dd6'
down_revision = '462e34736875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
