"""new models

Revision ID: 462e34736875
Revises: 61234ef31414
Create Date: 2024-10-27 22:13:02.810684

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '462e34736875'
down_revision = '61234ef31414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
