"""created_date datetime.now in minutes

Revision ID: 496ba59e6b92
Revises: e9b04e3d6860
Create Date: 2024-10-27 18:06:04.036185

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '496ba59e6b92'
down_revision = 'e9b04e3d6860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
