"""created_date datetime.now in minutes

Revision ID: 55c1df4ec69b
Revises: aa10d8c72418
Create Date: 2024-10-27 19:59:05.749724

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '55c1df4ec69b'
down_revision = 'aa10d8c72418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
