"""created_date datetime.now in minutes

Revision ID: 6038fbb59562
Revises: 271097c169a6
Create Date: 2024-10-27 18:02:44.696301

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '6038fbb59562'
down_revision = '271097c169a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
