"""created_date datetime.now in minutes

Revision ID: 61234ef31414
Revises: 55c1df4ec69b
Create Date: 2024-10-27 20:09:53.092869

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '61234ef31414'
down_revision = '55c1df4ec69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
