"""add models charity and donation in DB

Revision ID: 820f74f08241
Revises: a1747b520f5f
Create Date: 2024-10-26 17:30:49.792929

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '820f74f08241'
down_revision = 'a1747b520f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invested_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fully_invested', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('close_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('close_date')
        batch_op.drop_column('create_date')
        batch_op.drop_column('fully_invested')
        batch_op.drop_column('invested_amount')
        batch_op.drop_column('full_amount')

    # ### end Alembic commands ###
