"""add models charity and donation in DB

Revision ID: 839b6649adf9
Revises: 820f74f08241
Create Date: 2024-10-26 17:54:56.303746

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = '839b6649adf9'
down_revision = '820f74f08241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('full_amount')
        batch_op.drop_column('invested_amount')
        batch_op.drop_column('fully_invested')
        batch_op.drop_column('close_date')
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('close_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('fully_invested', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('invested_amount', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('full_amount', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
