"""add models charity and donation

Revision ID: a1747b520f5f
Revises: eaba25c99696
Create Date: 2024-10-26 17:20:10.687478

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'a1747b520f5f'
down_revision = 'eaba25c99696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
