"""created_date datetime.now in minutes

Revision ID: aa10d8c72418
Revises: 496ba59e6b92
Create Date: 2024-10-27 18:10:12.834156

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'aa10d8c72418'
down_revision = '496ba59e6b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
