"""new models

Revision ID: c78f1eede2ca
Revises: 21d732a671cb
Create Date: 2024-10-27 22:47:48.581777

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'c78f1eede2ca'
down_revision = '21d732a671cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
