"""created_date datetime.now in minutes

Revision ID: e9b04e3d6860
Revises: 6038fbb59562
Create Date: 2024-10-27 18:04:00.169304

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'e9b04e3d6860'
down_revision = '6038fbb59562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
