"""add models v1

Revision ID: ec148c683b34
Revises: 9be1af8bfbbd
Create Date: 2024-10-26 18:06:17.537222

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'ec148c683b34'
down_revision = '9be1af8bfbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.drop_index('ix_charityproject_id')

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_index('ix_donation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_index('ix_donation_id', ['id'], unique=False)

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.create_index('ix_charityproject_id', ['id'], unique=False)

    # ### end Alembic commands ###
