"""ok review

Revision ID: fac521ca3ac2
Revises: c78f1eede2ca
Create Date: 2024-11-10 21:55:21.135240

"""
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = 'fac521ca3ac2'
down_revision = 'c78f1eede2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
